import { type Call as TwilioCall } from '@twilio/voice-react-native-sdk';
import { match, P } from 'ts-pattern';
import { type AsyncStoreSlice } from '../../app';

export type CallInfo = {
  sid?: string;
  state?: string;
  to?: string;
  from?: string;
  initialConnectedTimestamp?: number;
  isMuted?: boolean;
  isOnHold?: boolean;
};

export const getCallInfo = (call: TwilioCall): CallInfo => {
  const sid = call.getSid();
  const state = call.getState();
  const to = call.getTo();
  const from = call.getFrom();

  const initialConnectedTimestamp = match(call.getInitialConnectedTimestamp())
    .with(undefined, () => undefined)
    .with(P._, (timestamp) => Number(timestamp))
    .exhaustive();

  const isMuted = Boolean(call.isMuted());
  const isOnHold = Boolean(call.isOnHold());

  return {
    sid,
    state,
    to,
    from,
    initialConnectedTimestamp,
    isMuted,
    isOnHold,
  };
};

export type BaseCall = {
  /**
   * When a call is generated by a thunk action, such as accepting a call
   * invite or making an outgoing call, we use the "requestId" that the thunk
   * generated.
   *
   * In the case of a call that we receive from the native layer that is not
   * associated with a thunk, such as accepting a call invite through the
   * notification or an existing call, we use "nanoid" to generate an ID.
   *
   * In both scenarios, "nanoid" is used - the thunk action creator uses
   * "nanoid" by default under the hood.
   */
  id: string;
} & AsyncStoreSlice<{
  action: {
    disconnect: AsyncStoreSlice;
    hold: AsyncStoreSlice;
    mute: AsyncStoreSlice;
    sendDigits: AsyncStoreSlice;
  };
  info: CallInfo;
}>;

export type OutgoingCallParameters = {
  to: string;
};

export type OutgoingCall = {
  direction: 'outgoing';
  params: OutgoingCallParameters;
} & BaseCall;
